# Generated by Django 3.2.6 on 2021-08-27 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='')),
                ('channels', models.IntegerField()),
                ('uploads', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('views', models.IntegerField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=20)),
                ('popular', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videoapp.uploader')),
            ],
        ),
    ]
