# Generated by Django 3.2.6 on 2021-08-27 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoapp', '0002_auto_20210828_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('views', models.IntegerField()),
                ('subscribers', models.IntegerField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('tags', models.CharField(max_length=20)),
                ('popular', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='videoapp.Category')),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
